DECLARE
  CURSOR DEPT_CURSOR IS
  SELECT DEPARTMENT_ID, DEPARTMENT_NAME
  FROM DEPARTMENTS
  WHERE DEPARTMENT_ID < 100
  ORDER BY DEPARTMENT_ID;
  
  CURSOR EMP_CURSOR(DEPT_NUM NUMBER) IS
  SELECT LAST_NAME, JOB_ID, HIRE_DATE, SALARY
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID < 120 AND DEPARTMENT_ID = DEPT_NUM;
  
  /*
    DEPT_CURSOR VARIABLES
  */
  
  V_DEPT_ID DEPARTMENTS.DEPARTMENT_ID%TYPE;
  V_DEPT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
  
   /*
    EMP_CURSOR VARIABLES
   */
   
   V_LAST_NAME EMPLOYEES.LAST_NAME%TYPE;
   V_JOB_ID EMPLOYEES.JOB_ID%TYPE;
   V_HIRE_DATE EMPLOYEES.HIRE_DATE%TYPE;
   V_SALARY EMPLOYEES.SALARY%TYPE;
   
BEGIN
  OPEN DEPT_CURSOR;
  LOOP
    FETCH dept_cursor INTO v_dept_id, v_dept_name;
    EXIT WHEN DEPT_CURSOR%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('Department Number: ' || V_DEPT_ID || '  ---  Department Name : ' || V_DEPT_NAME);
    OPEN EMP_CURSOR(v_dept_id);
    LOOP
      FETCH EMP_CURSOR INTO V_LAST_NAME, V_JOB_ID, V_HIRE_DATE, V_SALARY;
       EXIT WHEN EMP_CURSOR%NOTFOUND;
       DBMS_OUTPUT.PUT_LINE(V_LAST_NAME || '  ---  ' || V_JOB_ID || '  ---  ' || V_HIRE_DATE || '  ---  ' || V_SALARY);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('-------------------------------------------------------------------------------------------');
    CLOSE EMP_CURSOR;
  END LOOP;
  CLOSE DEPT_CURSOR;
END;