DECLARE
  V_NUM NUMBER := &TOPEARNERS;
  SAL EMPLOYEES.SALARY%TYPE;
  
  CURSOR C_EMP_CURSOR IS
    SELECT SALARY
    FROM EMPLOYEES
    ORDER BY SALARY DESC;
    
BEGIN

  OPEN C_EMP_CURSOR;
  LOOP
    EXIT WHEN (NOT C_EMP_CURSOR%FOUND) OR C_EMP_CURSOR%ROWCOUNT = V_NUM;
    FETCH C_EMP_CURSOR INTO SAL;
    INSERT INTO TOP_SALARIES VALUES(SAL);
  END LOOP;
  CLOSE C_EMP_CURSOR;

END;
/
/*
  To display the rows with a SELECT statement
*/
SELECT *
FROM TOP_SALARIES;

/*
  To empty the TOP_SALARIES table after the test;
*/
DELETE FROM TOP_SALARIES
WHERE 1=1;